server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    region: ${EUREKA_REGION:dev-region-1}

spring:
  application:
    name: claimspindel

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: s3-dev-route
              uri: lb://brazz-nossel
              predicates:
                - Path=/**
                - Claims=role,devrole
              filters:
              - RewritePath=/s3,/s3/dev
            - id: s3-admin-route
              uri: lb://brazz-nossel
              predicates:
                - Path=/**
                - Claims=role,adminrole	
              filters:
              - RewritePath=/s3,/s3/admin							
          globalcors:
            add-to-simple-url-handler-mapping: true
          discovery:
            locator:
              lower-case-service-id: true
              enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH2_ISSUER_URI:http://steel-hammer-keycloak:7081/realms/dev}
          jwk-set-uri: ${OAUTH2_ISSUER_URI:http://steel-hammer-keycloak:7081/realms/dev}/protocol/openid-connect/certs
